-- Rename existing CRM objects in place. Billing tables are intentionally removed.
BEGIN;
DROP TABLE "historico_pagamento";
DROP TABLE "assinatura";
DROP TABLE "plano";
ALTER TABLE "usuario" RENAME COLUMN "senha" TO "password";
ALTER TABLE "usuario" RENAME COLUMN "perfil" TO "profile";
ALTER TABLE "usuario" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "usuario" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "usuario" RENAME COLUMN "nome" TO "name";
ALTER TABLE "usuario" RENAME COLUMN "url_foto" TO "photo_url";
ALTER TABLE "usuario" RENAME COLUMN "email_confirmado" TO "email_confirmed";
ALTER TABLE "usuario" RENAME COLUMN "token_confirmacao_email" TO "token_confirmation_email";
ALTER TABLE "usuario" RENAME COLUMN "token_expira_em" TO "token_expires_at";
ALTER TABLE "usuario" RENAME TO "users";
ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "users" ALTER COLUMN "profile" SET DEFAULT 'user';
ALTER TABLE "loja" RENAME COLUMN "id_lojista" TO "store_owner_id";
ALTER TABLE "loja" RENAME COLUMN "cnpj" TO "tax_id";
ALTER TABLE "loja" RENAME COLUMN "nome_empresa" TO "company_name";
ALTER TABLE "loja" RENAME COLUMN "inscricao_municipal" TO "registration_municipal";
ALTER TABLE "loja" RENAME COLUMN "inscricao_estadual" TO "registration_state";
ALTER TABLE "loja" RENAME COLUMN "regime_tributario" TO "regime_tax";
ALTER TABLE "loja" RENAME COLUMN "portal_da_empresa" TO "portal_company";
ALTER TABLE "loja" RENAME COLUMN "atividade_principal" TO "activity_primary";
ALTER TABLE "loja" RENAME COLUMN "descricao_atividade" TO "description_activity";
ALTER TABLE "loja" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "loja" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "loja" RENAME COLUMN "url_foto" TO "photo_url";
ALTER TABLE "loja" RENAME COLUMN "wpp_configurado" TO "wpp_configured";
ALTER TABLE "loja" RENAME COLUMN "wpp_instancia" TO "wpp_instance";
ALTER TABLE "loja" RENAME COLUMN "distribuicao_automatica" TO "distribution_automatic";
ALTER TABLE "loja" RENAME COLUMN "integracoes_liberadas" TO "integrations_enabled";
ALTER TABLE "loja" RENAME TO "stores";
ALTER TABLE "cargo" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "cargo" RENAME COLUMN "cargo" TO "role";
ALTER TABLE "cargo" RENAME COLUMN "funcionalidades" TO "features";
ALTER TABLE "cargo" RENAME TO "roles";
ALTER TABLE "historico_loja" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "historico_loja" RENAME COLUMN "tipo_evento" TO "type_event";
ALTER TABLE "historico_loja" RENAME COLUMN "descricao" TO "description";
ALTER TABLE "historico_loja" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "historico_loja" RENAME TO "store_histories";
ALTER TABLE "lojista" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "lojista" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "lojista" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "lojista" RENAME COLUMN "token_cliente_meta" TO "token_customer_meta";
ALTER TABLE "lojista" RENAME COLUMN "token_cliente_olx" TO "token_customer_olx";
ALTER TABLE "lojista" RENAME TO "store_owners";
ALTER TABLE "store_owners" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "endereco_loja" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "endereco_loja" RENAME COLUMN "cep" TO "postal_code";
ALTER TABLE "endereco_loja" RENAME COLUMN "uf" TO "state";
ALTER TABLE "endereco_loja" RENAME COLUMN "cidade" TO "city";
ALTER TABLE "endereco_loja" RENAME COLUMN "rua" TO "street";
ALTER TABLE "endereco_loja" RENAME COLUMN "numero" TO "number";
ALTER TABLE "endereco_loja" RENAME COLUMN "bairro" TO "district";
ALTER TABLE "endereco_loja" RENAME COLUMN "complemento" TO "complement";
ALTER TABLE "endereco_loja" RENAME COLUMN "filial" TO "branch";
ALTER TABLE "endereco_loja" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "endereco_loja" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "endereco_loja" RENAME TO "store_addresses";
ALTER TABLE "contato_loja" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "contato_loja" RENAME COLUMN "nome" TO "name";
ALTER TABLE "contato_loja" RENAME COLUMN "celular" TO "mobile";
ALTER TABLE "contato_loja" RENAME COLUMN "telefone" TO "phone";
ALTER TABLE "contato_loja" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "contato_loja" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "contato_loja" RENAME TO "store_contacts";
ALTER TABLE "colaborador" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "colaborador" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "colaborador" RENAME COLUMN "url_foto" TO "photo_url";
ALTER TABLE "colaborador" RENAME COLUMN "nome" TO "name";
ALTER TABLE "colaborador" RENAME COLUMN "documento_fiscal" TO "tax_id";
ALTER TABLE "colaborador" RENAME COLUMN "observacoes" TO "notes";
ALTER TABLE "colaborador" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "colaborador" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "colaborador" RENAME COLUMN "telefone_complementar" TO "phone_additional";
ALTER TABLE "colaborador" RENAME TO "employees";
ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "cliente" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "cliente" RENAME COLUMN "nome" TO "name";
ALTER TABLE "cliente" RENAME COLUMN "tipo_pessoa" TO "type_person";
ALTER TABLE "cliente" RENAME COLUMN "documento_fiscal" TO "tax_id";
ALTER TABLE "cliente" RENAME COLUMN "rg" TO "identity_number";
ALTER TABLE "cliente" RENAME COLUMN "estrangeiro" TO "foreigner";
ALTER TABLE "cliente" RENAME COLUMN "genero" TO "gender";
ALTER TABLE "cliente" RENAME COLUMN "data_nascimento" TO "birth_date";
ALTER TABLE "cliente" RENAME COLUMN "observacoes" TO "notes";
ALTER TABLE "cliente" RENAME COLUMN "telefone" TO "phone";
ALTER TABLE "cliente" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "cliente" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "cliente" RENAME COLUMN "versao" TO "version";
ALTER TABLE "cliente" RENAME COLUMN "url_avatar" TO "avatar_url";
ALTER TABLE "cliente" RENAME TO "customers";
ALTER TABLE "customers" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "anexo_cliente" RENAME COLUMN "id_arquivo" TO "file_id";
ALTER TABLE "anexo_cliente" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "anexo_cliente" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "anexo_cliente" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "anexo_cliente" RENAME TO "customer_attachments";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME COLUMN "versao" TO "version";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME COLUMN "atualizacao" TO "update";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME COLUMN "id_usuario_editor" TO "id_user_editor";
ALTER TABLE "historico_dados_cadastrais_cliente" RENAME TO "customer_registration_histories";
ALTER TABLE "cliente_colaborador" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "cliente_colaborador" RENAME COLUMN "id_colaborador" TO "employee_id";
ALTER TABLE "cliente_colaborador" RENAME COLUMN "observacoes" TO "notes";
ALTER TABLE "cliente_colaborador" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "cliente_colaborador" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "cliente_colaborador" RENAME TO "customer_employees";
ALTER TABLE "endereco_cliente" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "endereco_cliente" RENAME COLUMN "cep" TO "postal_code";
ALTER TABLE "endereco_cliente" RENAME COLUMN "uf" TO "state";
ALTER TABLE "endereco_cliente" RENAME COLUMN "municipio" TO "city";
ALTER TABLE "endereco_cliente" RENAME COLUMN "endereco" TO "address";
ALTER TABLE "endereco_cliente" RENAME COLUMN "bairro" TO "district";
ALTER TABLE "endereco_cliente" RENAME COLUMN "numero" TO "number";
ALTER TABLE "endereco_cliente" RENAME COLUMN "complemento" TO "complement";
ALTER TABLE "endereco_cliente" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "endereco_cliente" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "endereco_cliente" RENAME TO "customer_addresses";
ALTER TABLE "atendimento" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "atendimento" RENAME COLUMN "id_cliente_temporario" TO "temporary_customer_id";
ALTER TABLE "atendimento" RENAME COLUMN "origem_atendimento" TO "deal_origin";
ALTER TABLE "atendimento" RENAME COLUMN "temperatura" TO "temperature";
ALTER TABLE "atendimento" RENAME COLUMN "descricao_atendimento" TO "description_deal";
ALTER TABLE "atendimento" RENAME COLUMN "observacao" TO "note";
ALTER TABLE "atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "atendimento" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "atendimento" RENAME COLUMN "titulo" TO "title";
ALTER TABLE "atendimento" RENAME COLUMN "modo_atendimento" TO "deal_mode";
ALTER TABLE "atendimento" RENAME COLUMN "atendimento_manual" TO "deal_manual";
ALTER TABLE "atendimento" RENAME TO "deals";
ALTER TABLE "anexo_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "anexo_atendimento" RENAME COLUMN "id_arquivo" TO "file_id";
ALTER TABLE "anexo_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "anexo_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "anexo_atendimento" RENAME COLUMN "nome_original" TO "name_original";
ALTER TABLE "anexo_atendimento" RENAME TO "deal_attachments";
ALTER TABLE "cliente_temporario" RENAME COLUMN "nome" TO "name";
ALTER TABLE "cliente_temporario" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "cliente_temporario" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "cliente_temporario" RENAME COLUMN "id_contato_api_externa" TO "external_contact_id";
ALTER TABLE "cliente_temporario" RENAME COLUMN "canal" TO "channel";
ALTER TABLE "cliente_temporario" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "cliente_temporario" RENAME TO "temporary_customers";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "id_colaborador" TO "employee_id";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "compartilhado_por" TO "shared_by";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "compartilhamento_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "compartilhamento_atendimento" RENAME TO "deal_shares";
ALTER TABLE "atendimento_responsaveis" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "atendimento_responsaveis" RENAME COLUMN "id_colaborador" TO "employee_id";
ALTER TABLE "atendimento_responsaveis" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "atendimento_responsaveis" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "atendimento_responsaveis" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "atendimento_responsaveis" RENAME TO "deal_assignees";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "id_responsavel" TO "assignee_id";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "nome" TO "name";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "concluida" TO "completed";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "hora_fim" TO "hour_end";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "hora_inicio" TO "hour_start";
ALTER TABLE "tarefas_atendimento" RENAME COLUMN "observacoes" TO "notes";
ALTER TABLE "tarefas_atendimento" RENAME TO "deal_tasks";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "observacoes" TO "notes";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "hora_inicio" TO "hour_start";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "hora_fim" TO "hour_end";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "concluida" TO "completed";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "visitas_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "visitas_atendimento" RENAME TO "deal_visits";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "comentario" TO "comment";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "motivo_perdido" TO "lost_reason";
ALTER TABLE "comentarios_atendimento" RENAME COLUMN "sub_motivo_perdido" TO "sub_lost_reason";
ALTER TABLE "comentarios_atendimento" RENAME TO "deal_comments";
ALTER TABLE "suspensao_atendimento" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "suspensao_atendimento" RENAME COLUMN "descricao" TO "description";
ALTER TABLE "suspensao_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "suspensao_atendimento" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "suspensao_atendimento" RENAME COLUMN "atendimentoId" TO "deal_id";
ALTER TABLE "suspensao_atendimento" RENAME TO "deal_suspensions";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "mensagem" TO "message";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "dados_antigos" TO "data_previous";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "dados_novos" TO "data_new";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "log_atividades_atendimento" RENAME COLUMN "tipo_evento" TO "type_event";
ALTER TABLE "log_atividades_atendimento" RENAME TO "deal_activity_logs";
ALTER TABLE "arquivos" RENAME COLUMN "usuario_id" TO "user_id";
ALTER TABLE "arquivos" RENAME COLUMN "entidade_id" TO "entity_id";
ALTER TABLE "arquivos" RENAME COLUMN "entidade" TO "entity";
ALTER TABLE "arquivos" RENAME COLUMN "nome" TO "name";
ALTER TABLE "arquivos" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "arquivos" RENAME COLUMN "validade" TO "expires_at";
ALTER TABLE "arquivos" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "arquivos" RENAME COLUMN "editado_em" TO "edited_at";
ALTER TABLE "arquivos" RENAME COLUMN "versao" TO "version";
ALTER TABLE "arquivos" RENAME COLUMN "tamanho" TO "size";
ALTER TABLE "arquivos" RENAME TO "files";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "nome" TO "name";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "validade" TO "expires_at";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "editado_em" TO "edited_at";
ALTER TABLE "arquivos_uuid" RENAME COLUMN "versao" TO "version";
ALTER TABLE "arquivos_uuid" RENAME TO "uuid_files";
ALTER TABLE "permissoes" RENAME COLUMN "usuario_id" TO "user_id";
ALTER TABLE "permissoes" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "permissoes" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "permissoes" RENAME COLUMN "funcionalidade" TO "feature";
ALTER TABLE "permissoes" RENAME TO "permissions";
ALTER TABLE "permissions" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "notificacao" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "notificacao" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "notificacao" RENAME COLUMN "mensagem" TO "message";
ALTER TABLE "notificacao" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "notificacao" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "notificacao" RENAME COLUMN "id_referencia" TO "id_reference";
ALTER TABLE "notificacao" RENAME TO "notifications";
ALTER TABLE "chat" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "chat" RENAME COLUMN "id_cliente" TO "customer_id";
ALTER TABLE "chat" RENAME COLUMN "id_cliente_temporario" TO "temporary_customer_id";
ALTER TABLE "chat" RENAME COLUMN "idAtendimento" TO "deal_id";
ALTER TABLE "chat" RENAME COLUMN "id_destinario_api_externa" TO "external_recipient_id";
ALTER TABLE "chat" RENAME COLUMN "canal" TO "channel";
ALTER TABLE "chat" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "chat" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "chat" RENAME COLUMN "id_anuncio_externo" TO "external_ad_id";
ALTER TABLE "chat" RENAME COLUMN "arquivado" TO "archived";
ALTER TABLE "chat" RENAME COLUMN "ultima_mensagem_cliente_em" TO "last_message_customer_at";
ALTER TABLE "chat" RENAME TO "chats";
ALTER TABLE "chat_responsaveis" RENAME COLUMN "id_chat" TO "chat_id";
ALTER TABLE "chat_responsaveis" RENAME COLUMN "id_colaborador" TO "employee_id";
ALTER TABLE "chat_responsaveis" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "chat_responsaveis" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "chat_responsaveis" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "chat_responsaveis" RENAME TO "chat_assignees";
ALTER TABLE "anexo_chat" RENAME COLUMN "id_chat" TO "chat_id";
ALTER TABLE "anexo_chat" RENAME COLUMN "id_arquivo" TO "file_id";
ALTER TABLE "anexo_chat" RENAME COLUMN "tipo_anexo" TO "attachment_type";
ALTER TABLE "anexo_chat" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "anexo_chat" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "anexo_chat" RENAME TO "chat_attachments";
ALTER TABLE "mensagem" RENAME COLUMN "idUsuario" TO "user_id";
ALTER TABLE "mensagem" RENAME COLUMN "id_chat" TO "chat_id";
ALTER TABLE "mensagem" RENAME COLUMN "id_destinario_api_externa" TO "external_recipient_id";
ALTER TABLE "mensagem" RENAME COLUMN "id_mensagem_externa" TO "external_message_id";
ALTER TABLE "mensagem" RENAME COLUMN "id_msg_ref_ext" TO "quoted_message_id";
ALTER TABLE "mensagem" RENAME COLUMN "anexo_mensagem" TO "attachment_url";
ALTER TABLE "mensagem" RENAME COLUMN "tipo_anexo" TO "attachment_type";
ALTER TABLE "mensagem" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "mensagem" RENAME COLUMN "conteudo" TO "content";
ALTER TABLE "mensagem" RENAME COLUMN "canal" TO "channel";
ALTER TABLE "mensagem" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "mensagem" RENAME COLUMN "remetente" TO "sender";
ALTER TABLE "mensagem" RENAME COLUMN "lido" TO "is_read";
ALTER TABLE "mensagem" RENAME COLUMN "origemInstagram" TO "origin_instagram";
ALTER TABLE "mensagem" RENAME COLUMN "metadados" TO "metadata";
ALTER TABLE "mensagem" RENAME TO "messages";
ALTER TABLE "mensagem_padrao" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "mensagem_padrao" RENAME COLUMN "titulo" TO "title";
ALTER TABLE "mensagem_padrao" RENAME COLUMN "conteudo" TO "content";
ALTER TABLE "mensagem_padrao" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "mensagem_padrao" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "mensagem_padrao" RENAME TO "message_templates";
ALTER TABLE "mensagem_pessoa" RENAME COLUMN "id_mensagem" TO "message_id";
ALTER TABLE "mensagem_pessoa" RENAME COLUMN "nome" TO "name";
ALTER TABLE "mensagem_pessoa" RENAME TO "message_persons";
ALTER TABLE "faq" RENAME COLUMN "titulo" TO "title";
ALTER TABLE "faq" RENAME COLUMN "categoria" TO "category";
ALTER TABLE "faq" RENAME COLUMN "conteudo" TO "content";
ALTER TABLE "faq" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "faq" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "faq" RENAME COLUMN "resumo" TO "summary";
ALTER TABLE "faq" RENAME TO "faqs";
ALTER TABLE "faqs" ALTER COLUMN "status" SET DEFAULT 'draft';
ALTER TABLE "tags_faq" RENAME COLUMN "nome" TO "name";
ALTER TABLE "tags_faq" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "tags_faq" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "tags_faq" RENAME TO "faq_tags";
ALTER TABLE "ticket_suporte" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "ticket_suporte" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "ticket_suporte" RENAME COLUMN "titulo" TO "title";
ALTER TABLE "ticket_suporte" RENAME COLUMN "assunto" TO "subject";
ALTER TABLE "ticket_suporte" RENAME COLUMN "mensagem" TO "message";
ALTER TABLE "ticket_suporte" RENAME COLUMN "prioridade" TO "priority";
ALTER TABLE "ticket_suporte" RENAME COLUMN "tipo" TO "type";
ALTER TABLE "ticket_suporte" RENAME COLUMN "categoria" TO "category";
ALTER TABLE "ticket_suporte" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "ticket_suporte" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "ticket_suporte" RENAME TO "support_tickets";
ALTER TABLE "support_tickets" ALTER COLUMN "status" SET DEFAULT 'open';
ALTER TABLE "ticket_historico" RENAME COLUMN "evento" TO "event";
ALTER TABLE "ticket_historico" RENAME COLUMN "acao" TO "action";
ALTER TABLE "ticket_historico" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "ticket_historico" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "ticket_historico" RENAME TO "ticket_histories";
ALTER TABLE "resposta_ticket" RENAME COLUMN "id_usuario" TO "user_id";
ALTER TABLE "resposta_ticket" RENAME COLUMN "resposta" TO "reply";
ALTER TABLE "resposta_ticket" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "resposta_ticket" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "resposta_ticket" RENAME TO "ticket_replies";
ALTER TABLE "anexo_suporte" RENAME COLUMN "id_resposta" TO "id_reply";
ALTER TABLE "anexo_suporte" RENAME COLUMN "id_arquivo" TO "file_id";
ALTER TABLE "anexo_suporte" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "anexo_suporte" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "anexo_suporte" RENAME COLUMN "nome_original" TO "name_original";
ALTER TABLE "anexo_suporte" RENAME TO "support_attachments";
ALTER TABLE "imagem_publica" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "imagem_publica" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "imagem_publica" RENAME COLUMN "id_arquivo" TO "file_id";
ALTER TABLE "imagem_publica" RENAME TO "public_images";
ALTER TABLE "tags" RENAME COLUMN "nome" TO "name";
ALTER TABLE "tags" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "tags" RENAME COLUMN "atualizado_em" TO "updated_at";
ALTER TABLE "tags" RENAME COLUMN "cor" TO "color";
ALTER TABLE "tags" RENAME COLUMN "descricao" TO "description";
ALTER TABLE "tags" RENAME COLUMN "id_loja" TO "store_id";
ALTER TABLE "atendimento_tag" RENAME COLUMN "id_atendimento" TO "deal_id";
ALTER TABLE "atendimento_tag" RENAME COLUMN "criado_em" TO "created_at";
ALTER TABLE "atendimento_tag" RENAME TO "deal_tags";
ALTER INDEX "usuario_email_key" RENAME TO "users_email_key";
ALTER TABLE "users" RENAME CONSTRAINT "usuario_pkey" TO "users_pkey";
ALTER INDEX "loja_cnpj_key" RENAME TO "stores_tax_id_key";
ALTER TABLE "stores" RENAME CONSTRAINT "loja_id_lojista_fkey" TO "stores_store_owner_id_fkey";
ALTER INDEX "loja_id_lojista_key" RENAME TO "stores_store_owner_id_key";
ALTER TABLE "stores" RENAME CONSTRAINT "loja_pkey" TO "stores_pkey";
ALTER INDEX "cargo_id_loja_cargo_key" RENAME TO "roles_store_id_role_key";
ALTER TABLE "roles" RENAME CONSTRAINT "cargo_id_loja_fkey" TO "roles_store_id_fkey";
ALTER TABLE "roles" RENAME CONSTRAINT "cargo_pkey" TO "roles_pkey";
ALTER TABLE "store_histories" RENAME CONSTRAINT "historico_loja_id_loja_fkey" TO "store_histories_store_id_fkey";
ALTER TABLE "store_histories" RENAME CONSTRAINT "historico_loja_pkey" TO "store_histories_pkey";
ALTER TABLE "store_owners" RENAME CONSTRAINT "lojista_id_usuario_fkey" TO "store_owners_user_id_fkey";
ALTER INDEX "lojista_id_usuario_key" RENAME TO "store_owners_user_id_key";
ALTER TABLE "store_owners" RENAME CONSTRAINT "lojista_pkey" TO "store_owners_pkey";
ALTER TABLE "store_addresses" RENAME CONSTRAINT "endereco_loja_id_loja_fkey" TO "store_addresses_store_id_fkey";
ALTER TABLE "store_addresses" RENAME CONSTRAINT "endereco_loja_pkey" TO "store_addresses_pkey";
ALTER TABLE "store_contacts" RENAME CONSTRAINT "contato_loja_id_loja_fkey" TO "store_contacts_store_id_fkey";
ALTER TABLE "store_contacts" RENAME CONSTRAINT "contato_loja_pkey" TO "store_contacts_pkey";
ALTER INDEX "colaborador_documento_fiscal_key" RENAME TO "employees_tax_id_key";
ALTER INDEX "colaborador_id_loja_documento_fiscal_key" RENAME TO "employees_store_id_tax_id_key";
ALTER TABLE "employees" RENAME CONSTRAINT "colaborador_id_loja_fkey" TO "employees_store_id_fkey";
ALTER TABLE "employees" RENAME CONSTRAINT "colaborador_id_usuario_fkey" TO "employees_user_id_fkey";
ALTER INDEX "colaborador_id_usuario_key" RENAME TO "employees_user_id_key";
ALTER TABLE "employees" RENAME CONSTRAINT "colaborador_pkey" TO "employees_pkey";
ALTER INDEX "cliente_documento_fiscal_id_loja_key" RENAME TO "customers_tax_id_store_id_key";
ALTER INDEX "cliente_email_id_loja_key" RENAME TO "customers_email_store_id_key";
ALTER TABLE "customers" RENAME CONSTRAINT "cliente_id_loja_fkey" TO "customers_store_id_fkey";
ALTER TABLE "customers" RENAME CONSTRAINT "cliente_pkey" TO "customers_pkey";
ALTER TABLE "customer_attachments" RENAME CONSTRAINT "anexo_cliente_id_arquivo_fkey" TO "customer_attachments_file_id_fkey";
ALTER INDEX "anexo_cliente_id_arquivo_key" RENAME TO "customer_attachments_file_id_key";
ALTER TABLE "customer_attachments" RENAME CONSTRAINT "anexo_cliente_id_cliente_fkey" TO "customer_attachments_customer_id_fkey";
ALTER TABLE "customer_attachments" RENAME CONSTRAINT "anexo_cliente_pkey" TO "customer_attachments_pkey";
ALTER TABLE "customer_registration_histories" RENAME CONSTRAINT "historico_dados_cadastrais_cliente_id_cliente_fkey" TO "customer_registration_histories_customer_id_fkey";
ALTER TABLE "customer_registration_histories" RENAME CONSTRAINT "historico_dados_cadastrais_cliente_pkey" TO "customer_registration_histories_pkey";
ALTER TABLE "customer_employees" RENAME CONSTRAINT "cliente_colaborador_id_cliente_fkey" TO "customer_employees_customer_id_fkey";
ALTER TABLE "customer_employees" RENAME CONSTRAINT "cliente_colaborador_id_colaborador_fkey" TO "customer_employees_employee_id_fkey";
ALTER TABLE "customer_employees" RENAME CONSTRAINT "cliente_colaborador_pkey" TO "customer_employees_pkey";
ALTER TABLE "customer_addresses" RENAME CONSTRAINT "endereco_cliente_id_cliente_fkey" TO "customer_addresses_customer_id_fkey";
ALTER INDEX "endereco_cliente_id_cliente_key" RENAME TO "customer_addresses_customer_id_key";
ALTER TABLE "customer_addresses" RENAME CONSTRAINT "endereco_cliente_pkey" TO "customer_addresses_pkey";
ALTER INDEX "atendimento_atualizado_em_idx" RENAME TO "deals_updated_at_idx";
ALTER TABLE "deals" RENAME CONSTRAINT "atendimento_id_cliente_fkey" TO "deals_customer_id_fkey";
ALTER TABLE "deals" RENAME CONSTRAINT "atendimento_id_cliente_temporario_fkey" TO "deals_temporary_customer_id_fkey";
ALTER INDEX "atendimento_id_loja_criado_em_idx" RENAME TO "deals_store_id_created_at_idx";
ALTER TABLE "deals" RENAME CONSTRAINT "atendimento_id_loja_fkey" TO "deals_store_id_fkey";
ALTER INDEX "atendimento_id_loja_modo_atendimento_criado_em_idx" RENAME TO "deals_store_id_deal_mode_created_at_idx";
ALTER INDEX "atendimento_id_loja_status_criado_em_idx" RENAME TO "deals_store_id_status_created_at_idx";
ALTER INDEX "atendimento_origem_atendimento_idx" RENAME TO "deals_deal_origin_idx";
ALTER TABLE "deals" RENAME CONSTRAINT "atendimento_pkey" TO "deals_pkey";
ALTER INDEX "atendimento_status_idx" RENAME TO "deals_status_idx";
ALTER INDEX "atendimento_temperatura_idx" RENAME TO "deals_temperature_idx";
ALTER TABLE "deal_attachments" RENAME CONSTRAINT "anexo_atendimento_id_arquivo_fkey" TO "deal_attachments_file_id_fkey";
ALTER INDEX "anexo_atendimento_id_arquivo_key" RENAME TO "deal_attachments_file_id_key";
ALTER TABLE "deal_attachments" RENAME CONSTRAINT "anexo_atendimento_id_atendimento_fkey" TO "deal_attachments_deal_id_fkey";
ALTER TABLE "deal_attachments" RENAME CONSTRAINT "anexo_atendimento_pkey" TO "deal_attachments_pkey";
ALTER TABLE "temporary_customers" RENAME CONSTRAINT "cliente_temporario_pkey" TO "temporary_customers_pkey";
ALTER TABLE "deal_shares" RENAME CONSTRAINT "compartilhamento_atendimento_id_atendimento_fkey" TO "deal_shares_deal_id_fkey";
ALTER TABLE "deal_shares" RENAME CONSTRAINT "compartilhamento_atendimento_id_colaborador_fkey" TO "deal_shares_employee_id_fkey";
ALTER TABLE "deal_shares" RENAME CONSTRAINT "compartilhamento_atendimento_id_loja_fkey" TO "deal_shares_store_id_fkey";
ALTER TABLE "deal_shares" RENAME CONSTRAINT "compartilhamento_atendimento_pkey" TO "deal_shares_pkey";
ALTER TABLE "deal_assignees" RENAME CONSTRAINT "atendimento_responsaveis_id_atendimento_fkey" TO "deal_assignees_deal_id_fkey";
ALTER TABLE "deal_assignees" RENAME CONSTRAINT "atendimento_responsaveis_id_colaborador_fkey" TO "deal_assignees_employee_id_fkey";
ALTER INDEX "atendimento_responsaveis_id_colaborador_id_atendimento_idx" RENAME TO "deal_assignees_employee_id_deal_id_idx";
ALTER TABLE "deal_assignees" RENAME CONSTRAINT "atendimento_responsaveis_id_loja_fkey" TO "deal_assignees_store_id_fkey";
ALTER TABLE "deal_assignees" RENAME CONSTRAINT "atendimento_responsaveis_pkey" TO "deal_assignees_pkey";
ALTER TABLE "deal_tasks" RENAME CONSTRAINT "tarefas_atendimento_id_atendimento_fkey" TO "deal_tasks_deal_id_fkey";
ALTER TABLE "deal_tasks" RENAME CONSTRAINT "tarefas_atendimento_id_responsavel_fkey" TO "deal_tasks_assignee_id_fkey";
ALTER TABLE "deal_tasks" RENAME CONSTRAINT "tarefas_atendimento_pkey" TO "deal_tasks_pkey";
ALTER INDEX "visitas_atendimento_id_atendimento_concluida_idx" RENAME TO "deal_visits_deal_id_completed_idx";
ALTER TABLE "deal_visits" RENAME CONSTRAINT "visitas_atendimento_id_atendimento_fkey" TO "deal_visits_deal_id_fkey";
ALTER TABLE "deal_visits" RENAME CONSTRAINT "visitas_atendimento_pkey" TO "deal_visits_pkey";
ALTER TABLE "deal_comments" RENAME CONSTRAINT "comentarios_atendimento_id_atendimento_fkey" TO "deal_comments_deal_id_fkey";
ALTER INDEX "comentarios_atendimento_id_atendimento_motivo_perdido_idx" RENAME TO "deal_comments_deal_id_lost_reason_idx";
ALTER TABLE "deal_comments" RENAME CONSTRAINT "comentarios_atendimento_id_usuario_fkey" TO "deal_comments_user_id_fkey";
ALTER TABLE "deal_comments" RENAME CONSTRAINT "comentarios_atendimento_pkey" TO "deal_comments_pkey";
ALTER TABLE "deal_suspensions" RENAME CONSTRAINT "suspensao_atendimento_atendimentoId_fkey" TO "deal_suspensions_deal_id_fkey";
ALTER TABLE "deal_suspensions" RENAME CONSTRAINT "suspensao_atendimento_id_usuario_fkey" TO "deal_suspensions_user_id_fkey";
ALTER TABLE "deal_suspensions" RENAME CONSTRAINT "suspensao_atendimento_pkey" TO "deal_suspensions_pkey";
ALTER INDEX "log_atividades_atendimento_id_atendimento_criado_em_idx" RENAME TO "deal_activity_logs_deal_id_created_at_idx";
ALTER TABLE "deal_activity_logs" RENAME CONSTRAINT "log_atividades_atendimento_id_atendimento_fkey" TO "deal_activity_logs_deal_id_fkey";
ALTER INDEX "log_atividades_atendimento_id_atendimento_tipo_evento_idx" RENAME TO "deal_activity_logs_deal_id_type_event_idx";
ALTER TABLE "deal_activity_logs" RENAME CONSTRAINT "log_atividades_atendimento_id_usuario_fkey" TO "deal_activity_logs_user_id_fkey";
ALTER TABLE "deal_activity_logs" RENAME CONSTRAINT "log_atividades_atendimento_pkey" TO "deal_activity_logs_pkey";
ALTER TABLE "files" RENAME CONSTRAINT "arquivos_pkey" TO "files_pkey";
ALTER TABLE "uuid_files" RENAME CONSTRAINT "arquivos_uuid_pkey" TO "uuid_files_pkey";
ALTER TABLE "permissions" RENAME CONSTRAINT "permissoes_pkey" TO "permissions_pkey";
ALTER TABLE "permissions" RENAME CONSTRAINT "permissoes_usuario_id_fkey" TO "permissions_user_id_fkey";
ALTER TABLE "notifications" RENAME CONSTRAINT "notificacao_id_usuario_fkey" TO "notifications_user_id_fkey";
ALTER TABLE "notifications" RENAME CONSTRAINT "notificacao_pkey" TO "notifications_pkey";
ALTER INDEX "chat_criado_em_idx" RENAME TO "chats_created_at_idx";
ALTER TABLE "chats" RENAME CONSTRAINT "chat_idAtendimento_fkey" TO "chats_deal_id_fkey";
ALTER TABLE "chats" RENAME CONSTRAINT "chat_id_cliente_fkey" TO "chats_customer_id_fkey";
ALTER INDEX "chat_id_cliente_id_loja_canal_key" RENAME TO "chats_customer_id_store_id_channel_key";
ALTER TABLE "chats" RENAME CONSTRAINT "chat_id_cliente_temporario_fkey" TO "chats_temporary_customer_id_fkey";
ALTER INDEX "chat_id_cliente_temporario_id_loja_canal_key" RENAME TO "chats_temporary_customer_id_store_id_channel_key";
ALTER INDEX "chat_id_loja_canal_id_destinario_api_externa_idAtendimento_idx" RENAME TO "chats_store_id_channel_external_recipient_id_deal_id_idx";
ALTER INDEX "chat_id_loja_canal_id_destinario_api_externa_idx" RENAME TO "chats_store_id_channel_external_recipient_id_idx";
ALTER TABLE "chats" RENAME CONSTRAINT "chat_id_loja_fkey" TO "chats_store_id_fkey";
ALTER TABLE "chats" RENAME CONSTRAINT "chat_pkey" TO "chats_pkey";
ALTER TABLE "chat_assignees" RENAME CONSTRAINT "chat_responsaveis_id_chat_fkey" TO "chat_assignees_chat_id_fkey";
ALTER INDEX "chat_responsaveis_id_chat_id_colaborador_key" RENAME TO "chat_assignees_chat_id_employee_id_key";
ALTER TABLE "chat_assignees" RENAME CONSTRAINT "chat_responsaveis_id_colaborador_fkey" TO "chat_assignees_employee_id_fkey";
ALTER TABLE "chat_assignees" RENAME CONSTRAINT "chat_responsaveis_id_loja_fkey" TO "chat_assignees_store_id_fkey";
ALTER TABLE "chat_assignees" RENAME CONSTRAINT "chat_responsaveis_pkey" TO "chat_assignees_pkey";
ALTER TABLE "chat_attachments" RENAME CONSTRAINT "anexo_chat_id_arquivo_fkey" TO "chat_attachments_file_id_fkey";
ALTER INDEX "anexo_chat_id_arquivo_key" RENAME TO "chat_attachments_file_id_key";
ALTER TABLE "chat_attachments" RENAME CONSTRAINT "anexo_chat_id_chat_fkey" TO "chat_attachments_chat_id_fkey";
ALTER TABLE "chat_attachments" RENAME CONSTRAINT "anexo_chat_pkey" TO "chat_attachments_pkey";
ALTER TABLE "messages" RENAME CONSTRAINT "mensagem_idUsuario_fkey" TO "messages_user_id_fkey";
ALTER TABLE "messages" RENAME CONSTRAINT "mensagem_id_chat_fkey" TO "messages_chat_id_fkey";
ALTER TABLE "messages" RENAME CONSTRAINT "mensagem_pkey" TO "messages_pkey";
ALTER TABLE "message_templates" RENAME CONSTRAINT "mensagem_padrao_id_loja_fkey" TO "message_templates_store_id_fkey";
ALTER TABLE "message_templates" RENAME CONSTRAINT "mensagem_padrao_pkey" TO "message_templates_pkey";
ALTER TABLE "message_persons" RENAME CONSTRAINT "mensagem_pessoa_id_mensagem_fkey" TO "message_persons_message_id_fkey";
ALTER INDEX "mensagem_pessoa_id_mensagem_key" RENAME TO "message_persons_message_id_key";
ALTER TABLE "message_persons" RENAME CONSTRAINT "mensagem_pessoa_pkey" TO "message_persons_pkey";
ALTER TABLE "faqs" RENAME CONSTRAINT "faq_pkey" TO "faqs_pkey";
ALTER INDEX "faq_slug_key" RENAME TO "faqs_slug_key";
ALTER INDEX "tags_faq_nome_key" RENAME TO "faq_tags_name_key";
ALTER TABLE "faq_tags" RENAME CONSTRAINT "tags_faq_pkey" TO "faq_tags_pkey";
ALTER TABLE "support_tickets" RENAME CONSTRAINT "ticket_suporte_id_loja_fkey" TO "support_tickets_store_id_fkey";
ALTER TABLE "support_tickets" RENAME CONSTRAINT "ticket_suporte_id_usuario_fkey" TO "support_tickets_user_id_fkey";
ALTER TABLE "support_tickets" RENAME CONSTRAINT "ticket_suporte_pkey" TO "support_tickets_pkey";
ALTER TABLE "ticket_histories" RENAME CONSTRAINT "ticket_historico_id_ticket_fkey" TO "ticket_histories_id_ticket_fkey";
ALTER TABLE "ticket_histories" RENAME CONSTRAINT "ticket_historico_id_usuario_fkey" TO "ticket_histories_user_id_fkey";
ALTER TABLE "ticket_histories" RENAME CONSTRAINT "ticket_historico_pkey" TO "ticket_histories_pkey";
ALTER TABLE "ticket_replies" RENAME CONSTRAINT "resposta_ticket_id_ticket_fkey" TO "ticket_replies_id_ticket_fkey";
ALTER TABLE "ticket_replies" RENAME CONSTRAINT "resposta_ticket_id_usuario_fkey" TO "ticket_replies_user_id_fkey";
ALTER TABLE "ticket_replies" RENAME CONSTRAINT "resposta_ticket_pkey" TO "ticket_replies_pkey";
ALTER TABLE "support_attachments" RENAME CONSTRAINT "anexo_suporte_id_arquivo_fkey" TO "support_attachments_file_id_fkey";
ALTER INDEX "anexo_suporte_id_arquivo_key" RENAME TO "support_attachments_file_id_key";
ALTER TABLE "support_attachments" RENAME CONSTRAINT "anexo_suporte_id_resposta_fkey" TO "support_attachments_id_reply_fkey";
ALTER TABLE "support_attachments" RENAME CONSTRAINT "anexo_suporte_id_ticket_fkey" TO "support_attachments_id_ticket_fkey";
ALTER TABLE "support_attachments" RENAME CONSTRAINT "anexo_suporte_pkey" TO "support_attachments_pkey";
ALTER TABLE "public_images" RENAME CONSTRAINT "imagem_publica_id_arquivo_fkey" TO "public_images_file_id_fkey";
ALTER INDEX "imagem_publica_id_arquivo_key" RENAME TO "public_images_file_id_key";
ALTER TABLE "public_images" RENAME CONSTRAINT "imagem_publica_pkey" TO "public_images_pkey";
ALTER TABLE "tags" RENAME CONSTRAINT "tags_id_loja_fkey" TO "tags_store_id_fkey";
ALTER INDEX "tags_nome_id_loja_key" RENAME TO "tags_name_store_id_key";
ALTER TABLE "deal_tags" RENAME CONSTRAINT "atendimento_tag_id_atendimento_fkey" TO "deal_tags_deal_id_fkey";
ALTER INDEX "atendimento_tag_id_atendimento_id_tag_key" RENAME TO "deal_tags_deal_id_id_tag_key";
ALTER TABLE "deal_tags" RENAME CONSTRAINT "atendimento_tag_id_tag_fkey" TO "deal_tags_id_tag_fkey";
ALTER TABLE "deal_tags" RENAME CONSTRAINT "atendimento_tag_pkey" TO "deal_tags_pkey";
ALTER TABLE "_cargo_colaborador" RENAME TO "_role_employee";
ALTER TABLE "_role_employee" RENAME COLUMN "A" TO "old_a";
ALTER TABLE "_role_employee" RENAME COLUMN "B" TO "A";
ALTER TABLE "_role_employee" RENAME COLUMN "old_a" TO "B";
ALTER TABLE "_role_employee" RENAME CONSTRAINT "_cargo_colaborador_A_fkey" TO "_role_employee_B_fkey";
ALTER TABLE "_role_employee" RENAME CONSTRAINT "_cargo_colaborador_B_fkey" TO "_role_employee_A_fkey";
DROP INDEX "_cargo_colaborador_AB_unique";
DROP INDEX "_cargo_colaborador_B_index";
CREATE UNIQUE INDEX "_role_employee_AB_unique" ON "_role_employee"("A", "B");
CREATE INDEX "_role_employee_B_index" ON "_role_employee"("B");
CREATE FUNCTION pg_temp.translate_crm_value(value TEXT) RETURNS TEXT LANGUAGE SQL IMMUTABLE AS $$ SELECT COALESCE('{"diario": "daily", "semanal": "weekly", "mensal": "monthly", "trimestral": "quarterly", "semestral": "semiannual", "anual": "annual", "CRIACAO": "CREATION", "MUDANCA_STATUS": "CHANGE_STATUS", "ATRIBUICAO_RESPONSAVEL": "ASSIGNMENT_ASSIGNEE", "REMOCAO_RESPONSAVEL": "REMOVAL_ASSIGNEE", "ADICAO_COMENTARIO": "ADDITION_COMMENT", "AGENDAMENTO_VISITA": "SCHEDULING_VISIT", "CONFIRMACAO_VISITA": "CONFIRMATION_VISIT", "CONCLUSAO_VISITA": "COMPLETION_VISIT", "REMOCAO_VISITA": "REMOVAL_VISIT", "CRIACAO_TAREFA": "CREATION_TASK", "CONCLUSAO_TAREFA": "COMPLETION_TASK", "REMOCAO_TAREFA": "REMOVAL_TASK", "ALTERACAO_TIPO_ATENDIMENTO": "CHANGE_TYPE_DEAL", "ALTERACAO_DADOS_CLIENTE": "CHANGE_DATA_CUSTOMER", "ARQUIVAMENTO": "ARCHIVING", "DESARQUIVAMENTO": "UNARCHIVING", "ALTERACAO_TITULO": "CHANGE_TITLE", "ALTERACAO_OBSERVACAO": "CHANGE_NOTE", "ALTERACAO_TEMPERATURA": "CHANGE_TEMPERATURE", "ADICAO_ANEXO": "ADDITION_ATTACHMENT", "REMOCAO_ANEXO": "REMOVAL_ATTACHMENT", "COMPARTILHAMENTO": "SHARE", "SUSPENSAO_CRIADA": "SUSPENSION_CREATED", "SUSPENSAO_ATUALIZADA": "SUSPENSION_UPDATED", "SUSPENSAO_REMOVIDA": "SUSPENSION_REMOVED", "DISTRIBUICAO_CONFIGURADA": "DISTRIBUTION_CONFIGURED", "ATENDIMENTOS_REDISTRIBUIDOS": "DEALS_REDISTRIBUTED", "MONITORAMENTO_EXECUTADO": "MONITORING_EXECUTED", "ALTERACAO_NOME_TAREFA": "CHANGE_NAME_TASK", "ALTERACAO_OBSERVACOES_TAREFA": "CHANGE_NOTES_TASK", "ALTERACAO_RESPONSAVEL_TAREFA": "CHANGE_ASSIGNEE_TASK", "ALTERACAO_HORA_INICIO_TAREFA": "CHANGE_HOUR_START_TASK", "ALTERACAO_HORA_FIM_TAREFA": "CHANGE_HOUR_END_TASK", "ALTERACAO_DATA_TAREFA": "CHANGE_DATA_TASK", "cliente-temporario": "customer-temporary", "cliente": "customer", "loja": "STORE", "sistema": "SYSTEM", "fisica": "individual", "juridica": "legalEntity", "ativo": "active", "inativo": "inactive", "lojaCriada": "storeCreated", "lojaEditada": "storeEdited", "lojaDeletada": "storeDeleted", "colaboradorCriado": "employeeCreated", "colaboradorEditado": "employeeEdited", "colaboradorDeletado": "employeeDeleted", "clienteCriado": "customerCreated", "clienteEditado": "customerEdited", "clienteDeletado": "customerDeleted", "ticketAberto": "ticketOpen", "ticketResolvido": "ticketResolved", "ticketFechado": "ticketClosed", "integracaoAdicionada": "integrationAdded", "integracaoRemovida": "integrationRemoved", "mensagemEnviada": "messageSent", "mensagemRecebida": "messageReceived", "atendimentoCriado": "dealCreated", "atendimentoAtualizado": "dealUpdated", "atendimentoFinalizado": "dealFinalized", "vendaRealizada": "sellCompleted", "vendaCancelada": "sellCanceled", "Integração": "Integration", "Atendimentos": "Deals", "Conta": "Account", "Outros": "Other", "criar": "create", "responder": "reply", "alterar_status": "update_status", "urgente": "urgent", "aberto": "open", "em resolução": "at resolution", "fechado": "closed", "resolução": "resolution", "lojista": "storeOwner", "usuario": "user", "lojaVerDashboard": "storeViewDashboard", "lojaVerAtendimentos": "storeViewDeals", "lojaEditarExcluirAtendimento": "storeEditDeleteDeal", "lojaVincularAtendimentoUsuario": "storeLinkDealUser", "lojaTransferirAtendimento": "storeTransferDeal", "lojaVerChat": "storeViewChat", "lojaResponderChat": "storeReplyChat", "lojaCadastrarEditarClientes": "storeRegisterEditCustomers", "lojaPesquisarClientes": "storeSearchCustomers", "lojaGerenciarUsuarios": "storeManageUsers", "lojaGerenciarCargos": "storeManageRoles", "lojaConfigurarIntegracoes": "storeConfigureIntegrations", "lojaEditarDadosDaLoja": "storeEditDataOfStore", "lojaGerenciarSuspensoes": "storeManageSuspensions", "lojaVerTodosAtendimentos": "storeViewAllDeals", "lojaCriarAtendimentoManual": "storeCreateDealManual", "lojaReatribuirAtendimentos": "storeReassignDeals", "lojaGerenciarEquipe": "storeManageTeam", "lojaVerAtendimentosProprios": "storeViewDealsOwn", "lojaCriarAtendimentoProprio": "storeCreateDealOwn", "lojaGerenciarTarefasProprias": "storeManageTasksOwn", "lojaPreVendedorFinalizarAtendimento": "storePreSalespersonFinalizeDeal", "lojaVerMensagensPadrao": "storeViewMessagesTemplate", "lojaCriarMensagemPadrao": "storeCreateMessageTemplate", "lojaEditarMensagemPadrao": "storeEditMessageTemplate", "lojaDeletarMensagemPadrao": "storeDeleteMessageTemplate", "autopilotVerDashboard": "autopilotViewDashboard", "autopilotResponderTickets": "autopilotReplyTickets", "autopilotVerTickets": "autopilotViewTickets", "autopilotAlterarPainelRevenda": "autopilotUpdatePanelReseller", "autopilotAtualizarPermissoes": "autopilotUpdatePermissions", "autopilotCriarUsuarioAdmin": "autopilotCreateUserAdmin", "autopilotVerUsuariosAdmin": "autopilotViewUsersAdmin", "compra": "BUY", "venda": "SELL", "consignado": "CONSIGNMENT", "quente": "HOT", "frio": "COLD", "morno": "WARM", "preAtendimento": "preDeal", "atendimentoInicial": "dealInitial", "visita": "visit", "emNegociacao": "atNegotiation", "resgate": "recovery", "sucesso": "success", "perdido": "lost", "ligacao": "call", "carteira": "portfolio", "indicacao": "referral", "outros": "other", "financeiroCredito": "financialCredit", "propostaAvaliacao": "proposalValuation", "estoqueProduto": "inventoryProduct", "semRetorno": "withoutResult", "concorrenciaOutraLoja": "competitionOtherStore", "interesseIntencao": "interestIntent", "outrosMotivos": "otherReasons", "financiamentoNaoAprovado": "financingNotApproved", "scoreCreditoInsuficiente": "scoreCreditInsufficient", "entradaMuitoBaixa": "incomingVeryLow", "valorParcelaIncompativelRenda": "valueInstallmentIncompatibleIncome", "clienteSemCreditoDisponivel": "customerWithoutCreditAvailable", "condicaoFinanciamentoNaoAceita": "conditionFinancingNotAccepted", "clienteDesistiuAposReprovacao": "customerWithdrewAfterRejection", "bancoRecusouProposta": "bankRejectedProposal", "clienteNaoQuisInformarDadosCredito": "customerNotWantedProvideDataCredit", "clienteNaoGostouAvaliacao": "customerNotLikedValuation", "propostaIncompativelMercado": "proposalIncompatibleMarket", "avaliacaoAbaixoEsperado": "valuationBelowExpected", "clienteAchouPrecoAlto": "customerFoundPriceHigh", "pedidoDescontoAlemPermitido": "requestDiscountBeyondAllowed", "lojaNaoAceitouValorTroca": "storeNotAcceptedValueTradeIn", "valorPropostaAbaixoEsperado": "valueProposalBelowExpected", "divergenciaValoresNegociacao": "differenceValuesNegotiation", "semVeiculoInteresseEstoque": "withoutVehicleInterestInventory", "veiculoFoiVendidoAntesNegociacao": "vehicleWasSoldBeforeNegotiation", "veiculoAguardandoPreparacao": "vehicleAwaitingPreparation", "veiculoReservadoOutroCliente": "vehicleReservedOtherCustomer", "documentacaoPendente": "documentationPending", "veiculoTrocaNaoInteressa": "vehicleTradeInNotInterests", "modeloDesejadoNaoTrabalhadoLoja": "modelDesiredNotSupportedStore", "corVersaoIndisponivel": "colorVersionUnavailable", "clienteNaoRespondeu": "customerNotReplied", "clienteNaoRetornouAposProposta": "customerNotReturnedAfterProposal", "clienteBloqueouContato": "customerBlockedContact", "dadosContatoIncorretos": "dataContactIncorrect", "telefoneWhatsappInvalido": "phoneWhatsappInvalid", "clienteDisseRetornariaNaoRetornou": "customerSaidWouldReturnNotReturned", "clienteIgnorouMensagens": "customerIgnoredMessages", "clienteSumiuAposConversaInicial": "customerDisappearedAfterConversationInitial", "clienteNegociouOutraLoja": "customerNegotiatedOtherStore", "clienteJaComprouOutroVeiculo": "customerAlreadyPurchasedOtherVehicle", "recebeuPropostaMelhorConcorrencia": "receivedProposalBestCompetition", "escolheuOutroModeloMarca": "choseOtherModelBrand", "preferiuConcessionaria": "preferredDealership", "comprouParticular": "purchasedPrivate", "fechouOutraCidade": "closedOtherCity", "clienteDesistiuNegociacao": "customerWithdrewNegotiation", "clienteAdiouCompra": "customerPostponedBuy", "clientePensando": "customerThinking", "clienteApenasPesquisando": "customerOnlyResearching", "vaiEsperarNovoModelo": "willWaitNewModel", "vaiComprarProximoMes": "willBuyNextMonth", "vaiManterCarroAtual": "willKeepCarCurrent", "mudouIdeiaAposConversa": "changedIdeaAfterConversation", "clienteNaoVeioLoja": "customerNotCameStore", "moraLongeInviavelDeslocamento": "livesFarUnfeasibleTravel", "ficouDoenteImprevistosPessoal": "becameSickImprevistosPersonal", "atendimentoDuplicado": "dealDuplicate", "clienteAtendidoOutroVendedor": "customerServedOtherSalesperson", "clienteCarteiraRelacionamentoDireto": "customerPortfolioRelationshipDirect", "timingForaMomentoCompra": "timingOutsideMomentBuy", "solicitouPausaTemporaria": "requestedPauseTemporary", "outroMotivo": "otherReason", "publicado": "published", "rascunho": "draft", "PENDENTE": "PENDING", "VISUALIZADO": "VIEWED", "ARQUIVADO": "ARCHIVED", "NOVO_ATENDIMENTO": "NEW_DEAL", "NOVA_MENSAGEM": "NEW_MESSAGE", "MENSAGENS_NAO_LIDAS": "MESSAGES_NOT_READ", "TAREFA_CRIADA": "TASK_CREATED", "TAREFAS_DIA": "TASKS_DAY", "TAREFA_REALIZADA": "TASK_COMPLETED", "ATENDIMENTO_TRANSFERIDO": "DEAL_TRANSFERRED", "ATENDIMENTO_COMPARTILHADO": "DEAL_SHARED", "VISITA_AGENDADA": "VISIT_SCHEDULED", "VISITA_DIA": "VISIT_DAY", "VISITA_REALIZADA": "VISIT_COMPLETED", "TICKET_CRIADO": "TICKET_CREATED", "TICKET_SEM_RESPOSTA": "TICKET_WITHOUT_REPLY", "erro": "error", "pendente": "pending", "excluido": "deleted", "bloqueado": "blocked", "atendimento": "deal", "tarefa": "task", "comentario": "comment", "anexo": "attachment", "chat-anexo": "chat-attachment", "chat-anexo-upload": "chat-attachment-upload", "avatar-externo-cliente": "avatar-external-customer", "avatar-externo-cliente-temporario": "avatar-external-customer-temporary"}'::jsonb ->> value, value) $$;
UPDATE "users" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "users" SET "profile" = pg_temp.translate_crm_value("profile");
UPDATE "roles" SET "features" = (SELECT string_agg(pg_temp.translate_crm_value(item), ',' ORDER BY position) FROM unnest(string_to_array("features", ',')) WITH ORDINALITY AS parts(item, position));
UPDATE "store_histories" SET "type_event" = pg_temp.translate_crm_value("type_event");
UPDATE "store_owners" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "employees" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "customers" SET "type_person" = pg_temp.translate_crm_value("type_person");
UPDATE "customers" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "deals" SET "deal_origin" = pg_temp.translate_crm_value("deal_origin");
UPDATE "deals" SET "temperature" = pg_temp.translate_crm_value("temperature");
UPDATE "deals" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "deals" SET "deal_mode" = pg_temp.translate_crm_value("deal_mode");
UPDATE "deal_visits" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "deal_comments" SET "lost_reason" = pg_temp.translate_crm_value("lost_reason");
UPDATE "deal_comments" SET "sub_lost_reason" = pg_temp.translate_crm_value("sub_lost_reason");
UPDATE "deal_activity_logs" SET "type_event" = pg_temp.translate_crm_value("type_event");
UPDATE "files" SET "entity" = pg_temp.translate_crm_value("entity");
UPDATE "files" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "uuid_files" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "permissions" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "permissions" SET "feature" = pg_temp.translate_crm_value("feature");
UPDATE "notifications" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "notifications" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "messages" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "messages" SET "sender" = CASE "sender" WHEN 'cliente' THEN 'CUSTOMER' WHEN 'loja' THEN 'STORE' WHEN 'sistema' THEN 'SYSTEM' ELSE "sender" END;
UPDATE "faqs" SET "category" = pg_temp.translate_crm_value("category");
UPDATE "faqs" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "support_tickets" SET "priority" = pg_temp.translate_crm_value("priority");
UPDATE "support_tickets" SET "status" = pg_temp.translate_crm_value("status");
UPDATE "support_tickets" SET "type" = pg_temp.translate_crm_value("type");
UPDATE "support_tickets" SET "category" = pg_temp.translate_crm_value("category");
UPDATE "ticket_histories" SET "event" = pg_temp.translate_crm_value("event");
ALTER TABLE "chats" ADD COLUMN "ai_insight" JSONB, ADD COLUMN "ai_analyzed_at" TIMESTAMP(3);
ALTER TABLE "messages" ADD COLUMN "delivery_status" TEXT NOT NULL DEFAULT 'PENDING';
CREATE TABLE "store_customizations" (
    "id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "logo_light_url" TEXT,
    "logo_dark_url" TEXT,
    "favicon_url" TEXT,
    "login_background_url" TEXT,
    "primary_color" TEXT NOT NULL DEFAULT '#1E40AF',
    "secondary_color" TEXT NOT NULL DEFAULT '#F3F4F6',
    "accent_color" TEXT NOT NULL DEFAULT '#3B82F6',
    "opening_time" TEXT NOT NULL DEFAULT '08:00',
    "closing_time" TEXT NOT NULL DEFAULT '18:00',
    "working_days" JSONB,
    "commission_rules" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "store_customizations_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "inbound_events" (
    "id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "available_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "inbound_events_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "store_customizations_store_id_key" ON "store_customizations"("store_id");
CREATE UNIQUE INDEX "store_customizations_slug_key" ON "store_customizations"("slug");
CREATE INDEX "inbound_events_status_available_at_idx" ON "inbound_events"("status", "available_at");
CREATE UNIQUE INDEX "inbound_events_store_id_event_id_kind_key" ON "inbound_events"("store_id", "event_id", "kind");
ALTER TABLE "store_customizations" ADD CONSTRAINT "store_customizations_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;
